name: Go Formatter

on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  format:
    name: Format Go Code
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Check Go formatting
        run: |
          unformatted="$(gofmt -l .)"
           if [ -n "$unformatted" ]; then
            echo "The following files need gofmt:"
            echo "$unformatted"
            exit 1
           fi

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: format Go code"
